{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Speedtest Values",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  download as \"Download\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  upload as \"Upload\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select download, time as time from speedtest"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select upload, time as time from speedtest"
    }
   ]
  },
  {
   "title": "Ping Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ping as \"Ping\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}