version: "3.7"

services:

  grafana:
    restart: always
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/:/etc/grafana/provisioning/
    environment:
      MYSQL_PASSWORD: password1

  mariadb:
    image: mariadb:latest
    restart: always
    hostname: "mariadb"
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password1

 # phpmyadmin:
 #   image: phpmyadmin/phpmyadmin:latest
 #   ports:
 #     - 8000:80
 #   environment:
 #     - PMA_ARBITRARY=1
 #     - PMA_HOST=mariadb
  #  depends_on:
  #    - mariadb
 # web:
 #   image: nginx:1.17
  #  ports:
  #    - 80:80
  #  volumes:
  #    - /var/www/docker-study.loc/recipe-03/php:/var/www/myapp
   #   - /var/www/docker-study.loc/recipe-03/docker/site.conf:/etc/nginx/conf.d/site.conf
 #   depends_on:
  #    - php
  #    - mariadb

 # php:
  #  image: php:7.2-fpm
  #  volumes:
  #    - /var/www/docker-study.loc/recipe-03/php:/var/www/myapp
  #    - /var/www/docker-study.loc/recipe-03/docker/php.ini:/usr/local/etc/php/php.ini
  #  depends_on:
  #    - mariadb

volumes:
  mariadb-data:
  grafana-data:
