# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
deleteDatasources:
   - name: Mariadb
     orgId: 1
   - name: mariadb
     orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  - name: mariadb
    type: mysql
    url: mariadb:3306
    database: internet
    user: root
    secureJsonData:
      password: password1
    editable: true